version: "3.4"

volumes:
  leaderms-volume:

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - leaderms-volume:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
  adminer:
    image: adminer:latest
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db
      - ADMINER_DEFAULT_TYPE=mysql
      - ADMINER_DEFAULT_PORT=3306
      - ADMINER_DEFAULT_DB=${MYSQL_DATABASE}
  world:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      - /app/target
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    depends_on:
      - db
    command: bash -c "bin/run_leaderms_sql.sh && exec bin/launch_world.sh"
  login:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      - /app/target
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    ports:
      - "8484:8484"
    depends_on:
      - db
      - world
    command: bash -c "sleep 15 && bin/launch_login.sh"
  channel:
    build:
      context: .
    restart: always
    volumes:
      - ./:/app
      - /app/target
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    depends_on:
      - db
      - world
    ports:
      - "7575:7575"
    command: bash -c "sleep 15 && bin/launch_channel.sh"
